# Generated by Django 3.1.3 on 2020-11-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_auto_20201105_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
