# Generated by Django 3.1.3 on 2020-11-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_donation_is_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(),
        ),
    ]
