# Generated by Django 3.1.3 on 2020-11-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_auto_20201118_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
    ]
