# Generated by Django 3.1.3 on 2020-11-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0011_auto_20201118_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Dar', 'verbose_name_plural': 'Dary'},
        ),
        migrations.AlterModelOptions(
            name='insitution',
            options={'verbose_name': 'Instytucja', 'verbose_name_plural': 'Instytucje'},
        ),
    ]
